# Generated by Django 5.2.1 on 2025-05-20 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='name',
            field=models.CharField(default=True, max_length=255, verbose_name='Название чата'),
            preserve_default=False,
        ),
    ]
